blimp:
  mass: 3
  volume: 0.00
  drag_coefficients: [0.1, 0.1, 0.1]
  cross_section_areas: [0.05, 0.05, 0.08]
  inertia: [0.1, 0.1, 0.1]

motors:
  count: 4
  max_thrust: 10
  positions:
    - [-0.15, 0.0, 0.0]
    - [0.15, 0.0, 0.0]
    - [0.0, -0.15, 0.0]
    - [0.0, 0.15, 0.0]
  directions:
    - [0.0, 0.0, -1.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 0.0, -1.0]
  torque_dirs:
    - [0.0, 0.0, 1.0]
    - [0.0, 0.0, 1.0]
    - [0.0, 0.0, -1.0]
    - [0.0, 0.0, -1.0]
  torque_coeff: 0.01

physics:
  air_density: 1.225
  gravity: 9.81
  dt: 0.001

sim_json:
  listen_port: 9002
  listen_address: "127.0.0.1"

home:
  lat: 47.9945
  lon: 55.9638
  alt: 0.0
